extends RefCounted

## Portrait assets are keyed by the stable officer registry ID so that aliases and
## later name changes do not break the association.
const PATH_BY_OFFICER_ID := {
	"officer_q171411": "res://assets/officers/portraits/oda_nobunaga.png",
	"officer_q187550": "res://assets/officers/portraits/hashiba_hideyoshi.png",
	"officer_q171977": "res://assets/officers/portraits/tokugawa_ieyasu.png",
	"officer_q311080": "res://assets/officers/portraits/uesugi_kenshin.png",
	"officer_q276404": "res://assets/officers/portraits/takeda_shingen.png",
	"officer_q1156545": "res://assets/officers/portraits/mori_motonari.png",
	"officer_q1070082": "res://assets/officers/portraits/chosokabe_motochika.png",
	"officer_q1156288": "res://assets/officers/portraits/shimazu_yoshihiro.png",
	"officer_q943643": "res://assets/officers/portraits/hojo_ujiyasu.png",
	"officer_q1054305": "res://assets/officers/portraits/imagawa_yoshimoto.png",
	"officer_q705860": "res://assets/officers/portraits/yajiro.png",
	"officer_q10856548": "res://assets/officers/portraits/ichinomiya_narisuke.png",
	"officer_q11352614": "res://assets/officers/portraits/ichinomiya_zuihasai.png",
	"officer_q2266090": "res://assets/officers/portraits/ichijo_nobutatsu.png",
	"officer_q370505": "res://assets/officers/portraits/ichijo_kanesada.png",
	"officer_q11352818": "res://assets/officers/portraits/ichijo_fusamoto.png",
	"officer_q108530286": "res://assets/officers/portraits/ichiyanagi_nobutaka.png",
	"officer_q11352868": "res://assets/officers/portraits/ichiyanagi_naosue.png",
	"officer_q11352874": "res://assets/officers/portraits/ichiyanagi_naotaka.png",
	"officer_q11352887": "res://assets/officers/portraits/ichikuri_hogyu.png",
	"officer_q136520820": "res://assets/officers/portraits/isshiki_masahiro.png",
	"officer_q11353119": "res://assets/officers/portraits/isshiki_kazuma.png",
	"officer_q11353127": "res://assets/officers/portraits/isshiki_ujihisa.png",
	"officer_q11353137": "res://assets/officers/portraits/isshiki_naotomo.png",
	"officer_q18700613": "res://assets/officers/portraits/isshiki_yoshikiyo.png",
	"officer_q11353173": "res://assets/officers/portraits/ichimanda_akizane.png",
	"officer_q7496112": "res://assets/officers/portraits/shichiri_yorichika.png",
	"officer_q123415684": "res://assets/officers/portraits/mikami_suenao.png",
	"officer_q11354142": "res://assets/officers/portraits/mikami_terufusa.png",
	"officer_q22127284": "res://assets/officers/portraits/mitoya_munetada.png",
	"officer_q11354865": "res://assets/officers/portraits/miyoshi_yoshifusa.png",
	"officer_q5370666": "res://assets/officers/portraits/miyoshi_soi.png",
	"officer_q1058953": "res://assets/officers/portraits/miyoshi_jikkyu.png",
	"officer_q11354925": "res://assets/officers/portraits/miyoshi_masanaga.png",
	"officer_q11242378": "res://assets/officers/portraits/miyoshi_tamezo.png",
	"officer_q10865734": "res://assets/officers/portraits/miyoshi_yoshioki.png",
	"officer_q11354963": "res://assets/officers/portraits/miyoshi_nagayuki.png",
	"officer_q1064909": "res://assets/officers/portraits/miyoshi_nagayoshi.png",
	"officer_q23986581": "res://assets/officers/portraits/miyoshi_nagatora.png",
	"officer_q11354967": "res://assets/officers/portraits/miyoshi_nagayasu.png",
	"officer_q10524017": "res://assets/officers/portraits/miyake_yasusada.png",
	"officer_q108781564": "res://assets/officers/portraits/miyake_masatsugu.png",
	"officer_q11355078": "res://assets/officers/portraits/miyake_fusahiro.png",
	"officer_q11355442": "res://assets/officers/portraits/mito_kagemichi.png",
	"officer_q11355591": "res://assets/officers/portraits/miki_kunitsuna.png",
	"officer_q27920679": "res://assets/officers/portraits/miki_seikan.png",
	"officer_q11355682": "res://assets/officers/portraits/miki_naoyori.png",
	"officer_q11355703": "res://assets/officers/portraits/miki_michiaki.png",
	"officer_q11355719": "res://assets/officers/portraits/miki_akitsuna.png",
	"officer_q6862455": "res://assets/officers/portraits/mimura_iechika.png",
}

static func texture_for(officer_id: String) -> Texture2D:
	var path: String = PATH_BY_OFFICER_ID.get(officer_id, "")
	return load(path) as Texture2D if not path.is_empty() else null
