import json
from pathlib import Path
root=Path(__file__).resolve().parents[1];mp=root/'docs/portraits_history_modern_20261002_55.json';rows=json.loads(mp.read_text(encoding='utf-8'))
r=rows[49]
r['appearance_design']='Historical portrait: elderly Japanese man with bare shaved head, fine grey eyebrows, sparse pale moustache, narrow mature face, black-brown formal robe, muted warm brown chest panel and white crossed inner collar. No helmet or topknot. Facial details at source resolution are limited; infer natural three-dimensional facial anatomy without claiming certainty.'
r['prompt']=f'Create a polished modern Sengoku-game bust portrait of Niwa Nagahide. Reference image 1 is a historical portrait dated sixteenth century, source Fukui Prefectural Archives, unknown author. Use ONLY face, shaved head and clothing as reference: {r["appearance_design"]} Realistic Western oil painting, refined painterly strokes, natural Japanese features, realistic head neck and shoulders, strong clear eyes, believable age, beautiful dimensional light and cloth texture. Ignore source posture, distorted body proportions, setting, lettering and flat painted technique. Natural slightly turned chest, composed intent gaze, dignified confident expression. Ability total 94/150, moderate presentation. Entire head contained with 5 percent transparent margin. Head to mid-chest, square 1:1, target512x512, genuine transparent RGBA PNG. No text in any language, no emblems or heraldic badges, no scenery, no background paint or checkerboard, no frame or watermark, no fantasy objects. Do not reference commercial game artwork.'
rows[33]['basis']='Nakagawa Hidenari (秀成), Edo-period portrait owned by Hekiunji; Commons filename redirects to Hideshige, but Japanese metadata identifies 秀成. Not a verified lifetime likeness.'
for i in [0,6,9,32,33,50]:rows[i]['rights']='Commons public-domain tagging of historical artwork; source and license metadata saved alongside reference.'
supp={0:['https://hosei.ecats-library.jp/da/repository/00012840/nou_40_miyamoto.pdf'],1:['https://www.city.ome.tokyo.jp/uploaded/attachment/10138.pdf'],4:['https://da.dl.itc.u-tokyo.ac.jp/portal/assets/b95aef97-2268-6687-5062-2bd5f0007b31'],9:['https://www.denkoku-no-mori.yonezawa.yamagata.jp/pdf/nenpo/nenpo19.pdf'],14:['https://museum.ryukoku.ac.jp/exhibition/2019/series_06/images/list_feature.pdf'],17:['https://www.city.takasaki.gunma.jp/uploaded/attachment/40400.pdf'],27:['https://www.moralogy.jp/admin/wp-content/files/themes/mor/img_research/2yokoyama.pdf'],30:['https://www.town.oguchi.lg.jp/secure/12186/2_2_2_sengoku.pdf'],32:['https://mimt.jp/wp-content/uploads/2026/03/2022_23.pdf'],33:['https://www.city.taketa.oita.jp/material/files/group/23/bunkazailist20250310.pdf'],38:['https://8-daigakukoza.sakura.ne.jp/taniguti.pdf'],41:['https://jmapps.ne.jp/ngrhk/det.html?data_id=35417'],50:['https://www.mlit.go.jp/kankocho/jirei_shien/content/001475656.pdf'],53:['https://www.town.agui.lg.jp/cmsfiles/contents/0000000/348/chitashikoku.pdf']}
for i,urls in supp.items():rows[i]['supporting_research_urls']=urls;rows[i]['supporting_research_use']='Identity/biography/holding information only. No face or costume inferred from a text, other person or modern illustration.'
for r in rows:r['search_date']='2026-10-02/03';r['research_method']='Web image and text searches before generation; historical-asset provenance and reuse checked for adopted references.'
mp.write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
credit=['武将肖像の史料参照と再構成 / Historical references for officer portraits','完成画像はAIで新規に再構成した現代風油彩胸像です。史料は顔・髪・衣装のみの参考とし、構図・体型・姿勢・背景は継承していません。本人の容貌の確定的復元ではありません。','商用ゲームの肖像やその派生画像を入力・参考に使用していません。','']
for r in rows:
    if r['reference_paths']:credit += [r['name']+' — '+r['basis'],r['rights'],*r['sources'],'']
credit += ['上杉謙信像(模本)：京都大学総合博物館所蔵、京都大学貴重資料デジタルアーカイブ。','https://rmda.kulib.kyoto-u.ac.jp/item/rb00033866','原資料から顔・頭巾・装束の特徴のみを参考に、人体比率・姿勢・陰影・構図を変更してAI油彩肖像へ再構成。原画像そのものの配布ではありません。','外見史料を確認できなかった47名は独自の創作であり、歴史的な容貌の根拠があるとは扱っていません。']
(root/'assets/officers/portraits/ATTRIBUTION.txt').write_text('\n'.join(credit)+'\n',encoding='utf-8')
print(json.dumps(rows,ensure_ascii=True))
