import json
from portraits_history116 import ROOT,read,write
refs={x['index']:x for x in json.loads((ROOT/'docs/portrait_research_20261003_116/downloaded_refs.json').read_text(encoding='utf-8')) if x.get('reference_path')}
# Only inspected images, matching the named subject; one clothing source per person.
features={
2:('北条幻庵像・祐泉寺蔵','制作年代・作者未詳。公開画像の2013年は原画の制作年ではない。伝来肖像として扱う。','An elderly Japanese man, fully shaved head, long oval face, fine narrow eyes, thin lips, clean shaved face; charcoal black patterned Buddhist outer robes, white layered collar with a small pale green inner edge. No helmet or armor.'),
6:('北条氏康画像・早雲寺原本に由来する小田原城天守閣蔵画像','原本は室町時代。入力は小田原城天守閣蔵の模本画像で、模本制作年代は未確認。','Mature Japanese man with long narrow face, straight thin eyebrows, long nose, small moustache and small pointed chin beard, natural slightly receding hairline, black angular folded eboshi; pale blue-gray suikan robe with the sparse hanging plant and butterfly motifs shown, layered white collar and ochre inner collar, chest cords. Keep this formal Japanese fabric costume, never replace with armor.'),
8:('北条氏政像・法雲寺蔵','1803年、北条氏喬奉納。後世の肖像。早雲寺本とは区別。','Mature Japanese man with broad oval cheeks, fine eyebrows, narrow eyes, small neat moustache and small chin beard; tall black court kanmuri with its hanging tail, black formal sokutai robe with restrained texture and thin seam lines, a glimpse of red sleeve lining. No armor.'),
10:('北条氏直像・法雲寺蔵','1803年、北条氏喬奉納。後世の肖像。','Young adult Japanese man with full cheeks, smooth skin, slender arched eyebrows, narrow eyes, small dark moustache, clean chin; black tall kanmuri crown and trailing cloth, black patterned formal court robe, small red sleeve lining and white underlayers. No armor.'),
19:('北畠具教像・伊勢吉田文庫蔵','制作年代・作者未詳。公開画像の2013年は原画の制作年ではない。伝来肖像。','Mature Japanese man with elongated oval face, narrow eyes, long straight nose, narrow moustache and small dark chin beard; short black eboshi, olive gray-green formal robe with the distinct large bamboo and sasa leaf patterns visible on his sleeves, white layered collar. No invented armor.'),
40:('千葉親胤御影・久保神社蔵（親胤寺旧蔵）','江戸時代、千葉定胤作とされる。香取市解説で同定。少年武者を描いた後世の供養像。','A teenage Japanese warrior about seventeen, small slim oval face, youthful clean-shaven cheeks, dark eyes and tied long black hair visible flowing behind his head; dark subdued brown-black Japanese lamellar armor with narrow tan lacing as pictured, dark collar. Keep the documented young face and long hair, but no exaggerated hair flight, no copied leaping pose, spear or heroic pose.'),
44:('南部信直像・盛岡市中央公民館「南部家の名宝」掲載','作者・制作年代未詳。公開画像の日付と原画年代は区別。伝来武装像。','Mature Japanese warrior, broad pale face, thin black moustache, fine slanted eyebrows, stern narrow eyes; the referenced gold-black kabuto with two upward curved gold side ornaments and central gold crest, red laced black lamellar armor, red patterned armored sleeves, layered neck protection. Only the main warrior face and outfit: remove the severed head, sword, text and seated pose entirely. Calm bust, no weapons.'),
55:('口羽通良像・毛利博物館「毛利元就座備図」部分','江戸時代（1603–1868）、作者不詳。後世の群像から本人部分のみ。','Older Japanese warrior with elongated face, high cheekbones, narrow eyes, small moustache and short chin beard; brown-green segmented kabuto with white tie, black and white laced broad shoulder armor with red accents, blue-gray undergarment. Exclude surrounding figures, fans, text and seated body.'),
57:('古田重然（織部）像・遠藤元閑「茶之湯六宗匠之伝記」','元禄15年（1702）刊、国立国会図書館書誌。後世の木版本。無彩色原図を入力し、2020年彩色版は不採用。衣装の色は推定。','Older Japanese tea master, long lean face, pointed long nose, narrow thoughtful eyes, thin moustache and short pointed chin beard, short folded black eboshi with light cords; soft cloth suikan robe with the source round berry clusters and vine arabesque shapes, white collar and chest cords. Since the historical input is monochrome, interpret the cloth in muted warm gray and motifs in charcoal; these colors are artistic inference. No armor or modern colored reproduction.'),
59:('吉川元春肖像・早稲田大学図書館蔵','大学書誌は書写年不明。Commons記載16–17世紀は補助情報として留保する。伝来肖像。','Mature Japanese man with broad rounded face, slightly receding forehead, narrow eyes, long nose, thin moustache and short small chin beard; tall black kanmuri crown with trailing cloth, plain dark charcoal-black formal robe with red inner neckline. No armor.'),
60:('吉川広家像・東京大学史料編纂所データベース掲載','制作年代・作者未詳。公開画像の2011年を制作年代としない。伝来肖像。','Mature Japanese man with long broad oval face, high receding forehead, level fine eyebrows, narrow long eyes, long straight nose and clean-shaven chin; tall black court kanmuri with light cords and trailing cloth, black formal robe with subtle curling woven patterns and thin seam lines, red inner neck edge. No armor.'),
66:('吉田長利像・福岡市博物館蔵','黒田二十四騎の伝来肖像。博物館解説では1810年着手の画帖等の系統を紹介。入力画像の厳密な制作年・作者は未確認。','Mature Japanese warrior with rectangular face, short neat moustache, dark focused eyes; black ridged helmet with red visor and distinctive tall white rounded front plume, brown-black horizontal lamellar cuirass, black shoulder armor with red lacing and muted indigo undersleeves. Keep plume completely visible with transparent margin. No fan or weapons.'),
70:('吉見正頼像・毛利博物館「毛利元就座備図」部分','江戸時代（1603–1868）、作者不詳。後世の群像から本人部分のみ。','Mature Japanese warrior with long narrow face, deep cheek creases, fine moustache and short dark beard; dark brown kabuto with tall central vertical rectangular ornament and angular side fittings, brown chest armor with black rectangular front pieces, white and red laced shoulder armor, muted green sleeves. Remove neighboring warriors, fan and seated pose.'),
83:('国司元相像・毛利博物館「毛利元就座備図」部分','江戸時代（1603–1868）、作者不詳。後世の群像から本人部分のみ。','Older Japanese warrior with broad angular face, narrow eyes, short moustache and chin beard; brown-black helmet with small oval ringlike front ornament, dark red and navy laced lamellar shoulder armor, white outer battle vest with the flowing dark geometric patterns of the source and green collar. Remove every surrounding person and inscription; no weapons.'),
86:('土井利勝像・正定寺蔵','Commonsは江戸時代初期と記載。茨城県教育委員会は制作年代不詳とするため断定しない。晩年の礼装像。県サイト画像は転用せずPD-Art掲載画像を入力。','An elderly Japanese man with broad long face, receding hairline, lightly graying eyebrows, slightly hooded eyes, a small gray moustache and short gray chin stubble; black tall court kanmuri with hanging tail, black formal sokutai robe with restrained woven patterns and red sleeve lining, white collar. No armor, no young hero face.'),
91:('伝土岐頼純像（模写）・南泉寺原本に由来、東京大学史料編纂所データベース掲載','原本には1549年仁仙宗寿賛。入力模本の作者・制作年代未詳。土岐頼武像とする同定説もあるため頼純本人の確定的容貌と扱わない。','Japanese man with long oval face, fine straight eyebrows, narrow eyes, long nose, thin moustache and sparse small chin beard, black angular folded eboshi with thin cords; plain deep charcoal formal robe with cream layered collar. Keep only the traditionally attributed face and outfit; no armor. Realistic natural anatomy, no copied seated silhouette.'),
103:('城井鎮房像・天徳寺蔵','作者・制作年代未詳。伝来像。公開画像の2013年は制作年代としない。','Mature Japanese man with high brows and narrow dark eyes, long oval angular face, slim moustache and small beard; tall black kanmuri court crown and trailing cloth, black formal sokutai robe with understated woven texture and fine seams, white undercollar. No armor.'),
106:('堀尾吉晴像・春光院蔵','慶長16年（1611）6月、春龍玄済賛。松江歴史館出品目録で確認。1961年木村義男油彩は不採用。','Mature Japanese man with rounded cheeks, fine arched eyebrows, narrow dark eyes, a fine sparse moustache and small short chin hair; tall black kanmuri court crown and trailing fabric, deep black formal robe, understated pale gold and cream decorative motifs at sleeve edges, no armor.'),
108:('堀尾忠氏像（部分）・春光院蔵','制作年代・作者未詳。『雲州松江の歴史をひもとく』展示ガイド掲載。2013年は公開画像日付である。','Japanese man with long broad face, high receding forehead, fine sparse eyebrows, narrow eyes, straight broad nose, thin faint moustache and sparse short chin hair; tall black kanmuri with long trailing cloth, plain dark charcoal-black court robe and dark layered neckline. No armor.'),
112:('堀直寄寿像・狩野探幽筆、新潟県立歴史博物館蔵','寛永13年（1636）、還暦の寿像。新潟県立歴史博物館目録で確認。同時代肖像。','A Japanese elder around sixty, shaved or very closely shaved head, long thoughtful oval face and fine narrow eyes; muted ochre-gray loose Buddhist style fabric robe with black kesa across the upper chest, as in the historical portrait. No armor, helmet, sword or court crown; no copied cross-legged seated pose.'),
114:('堀秀政像・長慶寺蔵、和歌山市立博物館図録掲載','作者・制作年代未詳。自画とする伝承があるが確定しない。公開画像の2013年は制作年ではない。','Japanese man with completely shaved head, long narrow face, distinctive thick arched eyebrows, long narrow eyes, long pointed nose, clean-shaven face and thin lips; muted gray-brown loose robes with broad dark brown patterned kesa and small white inner collar. Retain the documented shaven religious appearance, no helmet, topknot or armor.')}
official={6:'https://ch.kanagawa-museum.jp/dm/gohojyo/relation/d_houjyo_03.html',40:'https://www.city.katori.lg.jp/culture_sport/bunkazai/isan/isan_vol061-070.html',57:'https://ndlsearch.ndl.go.jp/books/R100000002-I000007308541',59:'https://www.wul.waseda.ac.jp/kotenseki/html/nu06/nu06_05848/index.html',60:'https://www.town.kitahiroshima.lg.jp/site/kominkan/29673.html',66:'https://museum.city.fukuoka.jp/archives/leaflet/425/index02.html',86:'https://kyoiku.pref.ibaraki.jp/bunkazai/ken-171/',91:'https://www.rekihaku.gifu.gifu.jp/gmh/wp-content/themes/rekihaku/pdf/exhibition/kirin-mokuroku2020.pdf',103:'https://www.city.kitakyushu.lg.jp/files/000786250.pdf',106:'https://matsuerekishikan.sakura.ne.jp/rekishikan_n/wp-content/uploads/2022/06/horio_list.pdf',112:'https://nbz.or.jp/uploads/2020/12/a4c4c2d79e0b08b9bb6b28791b796e16.pdf'}
faces=['long lean face, low straight eyebrows, deep-set eyes and a wide nose','broad rounded face, fine arched brows, close-set eyes and rounded chin','angular rectangular face, broad brows, high cheekbones and square chin','small oval face, widely spaced eyes, thin lips and short nose','long oval face, hooded eyes, pronounced nose bridge and soft jaw','broad triangular face, dense brows, deep cheeks and narrow chin','narrow rectangular face, thin brows, broad nostrils and prominent jaw','full rounded cheeks, short straight nose, level brows and small chin','high cheekbones, long tapering chin, thick curved brows and narrow eyes','short square face, broad nose, gently drooping eyes and full lips','wide forehead, narrow cheekbones, long nose and thin relaxed lips','small broad face, slightly asymmetrical brows, rounded nose and strong jaw']
clothes=['plain charcoal kosode with muted brown sleeveless cloth shoulder garment','faded indigo kosode with a simple gray sleeveless kataginu','plain warm brown kosode with tan collar layers','muted olive-gray kosode beneath an unadorned brown cloth overrobe','simple navy kosode with a dark gray cloth kataginu','undyed beige kosode with a modest brown cloth overrobe','dull russet kosode with a restrained dark cloth shoulder vest','worn blue-gray kosode and a simple cream collar','plain dark teal kosode beneath a muted charcoal cloth overrobe','quiet gray kosode with an unadorned subdued olive cloth kataginu','plain muted umber kosode with faded indigo collar layers']
hair=['shaved-front Japanese chonmage with a small low tied topknot','natural receding dark hair neatly tied in a small Japanese topknot','short Japanese chonmage, shaved crown and tidy side hair','dark hair brushed back and tied into a simple compact Japanese topknot']
beards=['clean-shaven face','small neat moustache, clean chin','fine moustache and restrained small chin beard','light gray moustache and sparse short chin hair','clean-shaven face with natural slight stubble']
poses=['body angled slightly left, head turned toward viewer, quiet attentive gaze','body facing almost front, head turned gently right, thoughtful neutral expression','body angled right, head turned slightly left, steady calm eyes','relaxed shoulders facing viewer, chin slightly lowered and observant expression','small three-quarter shoulder turn left, face held upright with mild reserve']
rows=read()
for r in rows:
    i=r['index'];r['search_queries']=[f'"{r["name"]}" 肖像 所蔵',f'"{r["name"]}" 肖像 史料 -信長の野望 -ゲーム -AI']
    r['research_record_directory']='docs/portrait_research_20261003_116'
    r['ability_source']='data/derived/officers/officers_1546.json; total_ability / 150; high ability threshold >=120'
    if i in features:
        title,date,detail=features[i];ref=refs[i];r.update(historical_source_title=title,historical_date_note=date,adopted_features=detail,reference_paths=[ref['reference_path']],sources=[ref['url']]+([official[i]] if i in official else []),rights='Input historical image: Wikimedia Commons Public Domain / PD-Art reproduction as documented on the file page. Modern reproductions, commercial portraits and 2020 recolor are not used.',qa_reference_image_viewed=True,basis='historical_image',creative_inference='Natural three-dimensional anatomy, skin texture, lighting, new bust pose. Unknown or monochrome costume colors remain inference; no claim of definitive personal likeness.')
        subject=f'Input image 1 is {title}. {date} Use it ONLY for the named person FACE, HAIR, FACIAL HAIR, HEADGEAR and COSTUME. Essential traits to preserve: {detail} Do not copy flat painting technique, body proportions, pose, composition, neighboring people, inscriptions, or background.'
    else:
        age=28+(i*11)%39;detail=f'A Japanese man about {age}, {faces[i%len(faces)]}, {hair[(i//3)%4]}, {beards[(i//7)%5]}; {clothes[(i*3+i//11)%len(clothes)]}.'
        r.update(basis='independent_creative_appearance',adopted_features=detail,creative_inference='今回、本人の顔・服装を同定でき利用条件を確認した画像は確保できなかった。顔・年齢・髪・衣装の色は独自創作であり復元ではない。史料の不存在は断定しない。',reference_paths=[],sources=[])
        subject='No verified usable historical appearance image was secured in this research. Make an ORIGINAL creative period-plausible Japanese Sengoku man, never a definitive reconstruction or a copy of another real person. '+detail
    if i==2:r['rejected_reference_note']='宝泉寺の北条時長像は幻庵嫡男の肖像とされるため不採用。'
    if i==15:r['rejected_reference_note']='Hōjō Tsunashige.jpgの説明は綱重（氏信）であり綱成本人ではないため不採用。'
    if i==57:r['rejected_reference_note']='Furutaoribe color.jpg（2020年彩色）は不採用。1702年木版本の無彩色画像を入力。'
    if i==61:r['rejected_reference_note']='北広島町は本人肖像が残っていないため現代に描かせた旨を説明。現代委嘱イラストを入力に使わない。'
    if i==91:r['identity_uncertainty']='伝土岐頼純。頼武像とする説もある。伝承像の再構成として記録し本人の確定容貌とは断定しない。'
    direction=('High ability 134/150: dignified powerful dramatic bust, shoulders strongly turned, chin held confidently and commanding eyes facing viewer, slightly raised forearm folded across lower chest without hiding collar; sharpen expression and sculptural light while preserving the exact historical face and cloth costume.' if r['ability']>=120 else f'Ability {r["ability"]}/150 is below120: modest natural presence, understated pose and lighting, ordinary individual face, no exaggerated heroic beauty. Pose: {poses[(i*3)%5]}. Maintain excellent polished finish.')
    r['prompt']=f'''Use case: historical-scene. Asset: ONE individual game officer portrait for {r['name']}. {subject}\nPaint an original polished modern Japanese strategy-game BUST as REALISTIC WESTERN OIL PAINTING: dimensional living Japanese face, natural subtle skin and cloth textures, controlled painterly detail, expressive readable eyes. Western refers to painting technique only, never Western facial ethnicity or clothes. Realistic natural skull, neck and shoulder anatomy; do NOT imitate traditional painting or ukiyo-e bodily proportions. {direction}\nFRAMING IS CRITICAL: square 1:1 canvas, head through upper chest ONLY, not waist or seated legs. The entire top of hair, crown, helmet and plume must fit. Leave a continuous fully transparent top band of SIX percent of the square height above the very highest headgear/hair tip. Shoulders fit naturally with four percent side breathing room; chest can end at bottom. Face remains large and readable. Gently sculpted light from above-left, soft fill so eyes are visible, no colored rim glow.\nOutput true transparent-background RGBA PNG, final game production target512×512. Everything outside the person has alpha zero, including the six percent top band; no painted white, black, gray or checkerboard background. NO TEXT of any language anywhere (including Japanese), no calligraphy, numbers, caption, logo, watermark, frame, UI, scenery, separate symbols, halo, surrounding brushstroke cloud or floor shadow. No commercial game imagery, actors, fan art, AI reference imagery or copied character designs. No invented scars, crests, extravagant helmet decorations or fantasy armor. One person only.'''
write(rows)
print('Prompts prepared',len(rows),'historical refs',len(features))
