import json,re,html,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'docs/portraits_history_modern_20261003_102.json'
D=ROOT/'assets/officers/portraits/references/history_modern_20261003_102'
rows=json.loads(P.read_text(encoding='utf-8'))
downloaded={x['index']:x for x in json.loads((ROOT/'docs/portrait_research_20261003_102/downloaded_refs.json').read_text(encoding='utf-8')) if x.get('reference_path')}
DETAILS={
2:('002_Kuniyoshi.jpg','歌川国芳「太平記英勇伝 佐田陸奥守有正」','1847–1852年頃。江戸期の歴史物語に基づく後世の武者絵。本人の実際の外見を保証しない。','Historical Japanese man with forceful ordinary features, pronounced brows, short moustache and chin beard, thick loose dark hair as in the woodprint; dark indigo-blue lamellar armor with red lacing and red outer robe with subtle golden scroll motifs. Keep only his face, hair and clothes; absolutely no horse, staff, banner or weapons. Soften the exaggerated theatrical frown to a restrained firm gaze, correct all anatomical distortions.',['https://publicdomainq.net/utagawa-kuniyoshi-sassa-narimasa-0045915/','https://www.e-tmm.info/list_2023_ukiyoe.pdf']),
12:('012_Satake Yoshinobu.jpg','天徳寺所蔵「佐竹義宣像」','江戸時代。作者不詳。没後の肖像を含む。','Mature Japanese man in black lacquered kabuto without invented horns, white-and-dark-blue laced lamellar shoulder plates, dark cuirass with the pale circular disc present on the original and a grey metal facial menpo. Preserve visible eye region and original mask; do not expose or invent an uncovered lower face. The visible mouth detail belongs to the menpo. No weapons, no horse or seated stool.',[]),
15:('015_official.jpg','大庵寺所蔵「佐野昌綱像」／佐野市公開画像','1579年、狩野松栄筆・策彦周良賛とされる没後像。佐野市は狩野派の没後肖像と説明。','Mature Japanese man with shaved-front small topknot, lined lean oval face, high narrow brows, modest moustache and pointed neat chin beard. Pale cream-grey kataginu with subtly mottled floral fabric over light robe and deep green brocade chest layers and cords, rust-red inner collar. Preserve the garments of this one portrait, with realistic shoulder width and natural garment folds rather than flat oversized wings.',['https://www.city.sano.lg.jp/kurashi_gyosei/kanko_bunka_sports/bunka_dento/karasawa/3/8771.html','https://www.muse.pref.tochigi.lg.jp/exhibition/thema/2025hidesato/2025hujiwaranohidesato_list.pdf']),
21:('021_Hoshina Masayuki.jpg','土津神社所蔵「保科正之像」','江戸時代17世紀の平服像。作者不詳。画像は低解像度。','Older Japanese man, slim lined face, fine natural eyebrows, clean-shaven face, black court kanmuri with upright tip and curved rear attachment, black formal court robe and white neck collar. Keep clothing black, no armor and no invented facial hair.',['https://www.edo-tokyo-museum.or.jp/assets/img/2015/03/yae_list.pdf']),
36:('036_Kanematsu Masayoshi.jpg','兼松正吉肖像／東京大学史料編纂所データベース','歴史肖像。詳細制作年未確認。Commonsの2011年は画像データの日付で原画制作年ではない。','Japanese man with defined ordinary face, arched fine brows, slender moustache and short neat chin beard. Rounded black ribbed kabuto, gilded forehead trim, gold circular ornament with the small dark fierce face motif on the helmet top as in the reference; black layered armor with restrained red and gold accents and tan brocade sleeves. Preserve only face and armor, not the red fan, stool or swords. Keep the authentic ornament compact, do not invent antlers.',[]),
38:('038_Naitō Nobunari.jpg','安泰寺所蔵「内藤信成像」（村上市郷土資料館保存）','歴史肖像。詳細制作年未確認。Commonsの2013年は画像データの日付。','Older Japanese man, long lined face, prominent cheek creases, short fine brows, clean-shaven face. Black kanmuri with long rear strip, vermilion court robe with subtle tonal curling patterns, white neck collar. Natural narrow shoulders under the robe, no armor.',[]),
39:('039_official.jpg','藤基神社御神宝「内藤家歴代当主肖像画」第2代内藤信正像','江戸時代。藤基神社伝来、村上市郷土資料館寄託。詳細制作年未確認。','Older Japanese man with broad square ordinary face, fuller cheeks and chin, low straight eyebrows, lined skin, no added beard. Black court kanmuri with bent rear strip; muted deep red formal robe with restrained tonal scroll fabric and white collar. Preserve the specific face of the SECOND ruler painting, no armor.',['https://fujimotojinja.jp/shouzouga/']),
40:('040_official.jpg','藤基神社御神宝「内藤家歴代当主肖像画」第3代内藤信照像','江戸時代。藤基神社伝来、村上市郷土資料館寄託。詳細制作年未確認。','Older Japanese man with lean elongated face, narrow brows, deep cheek lines, small mouth, no added facial hair. Black kanmuri with long bent rear strip; dark red formal court robe, white collar. Preserve the specific face of the THIRD ruler painting, with natural human shoulders under the robe, no armor.',['https://fujimotojinja.jp/shouzouga/']),
47:('047_Naitō Masanaga.jpg','内藤政長画像／『いわき史料集成 第五冊』掲載','江戸時代17世紀の肖像。延岡市は狩野玄春筆と説明。Commons2013年は画像データの日付。','Japanese man with broad oval face, gentle narrow eyebrows, clean-shaven face. Black formal kanmuri with long rear strip, black court robe with closely spaced subtle green-grey arabesque woven fabric, red lining and pale neck collar. Preserve this formal clothing instead of armor.',['https://www.city.nobeoka.miyazaki.jp/soshiki/93/18159.html']),
49:('049_Naitō Masanari.jpg','日光東照宮所蔵「徳川二十将図」内藤正成部分（伝狩野永納）','江戸期とされる後世の群像画。伝狩野永納。Commons2013年は画像データの日付。','Mature Japanese man with broad ordinary face, thick eyebrows, modest moustache and short beard, shaved-front period topknot. Rust-red laced lamellar shoulder armor, brown chest plates with many small pale floral motifs, grey sleeves, green neck underlayer. Reference only the foreground named man and his clothes; exclude surrounding warriors and their armor. Bust-up only; no weapon.',[]),
54:('054_Naitō Okimori.jpg','善生寺所蔵「内藤興盛像」雲谷等竺筆・琢玄円磋賛','19世紀の後世像。2005年は掲載書籍出版年で原画制作年ではない。','Middle-aged Japanese man, full ordinary face with narrow relaxed eyes, defined nose, modest short moustache and small pointed chin beard; black kanmuri with long rear strip. Black tonal scrolling formal robe with restrained red neck lining and white collar. No armor, do not copy inscription.',[]),
69:('069_Maeda Toshiie.jpg','前田利家肖像（個人所蔵品の忠実な複製としてCommons公開）','1867年以前と記載。作者不詳・個人所蔵、具体的伝来未確認。長齢寺本・宝円寺本と断定しない。','Mature Japanese man with shaved-front small topknot, narrow oval face, gently arched slim brows, fine moustache and short chin beard. Black outer robe with restrained scattered small golden floral motifs and red lining over muted gold-tan floral brocade chest layers, cream collar. Preserve this one source clothing only; no armor or helmet, no wooden seat.',[]),
70:('070_Maeda Toshitsune.png','那谷寺所蔵「前田利常像」','歴史肖像。Commons2016年は画像データの日付。制作時期は那谷寺・小松市解説と区別して記録。','Mature Japanese man with round full face, delicate curved brows, short modest moustache and tiny neat chin beard. Black formal kanmuri with upright tip and curved rear attachment, subtly patterned black court robe with red lining and pale grey neck collar. Lifelike naturally colored lips, no makeup-like saturated red lips, no armor.',['https://www.natadera.com/meguru_houmotsukan/index.html','https://www.city.komatsu.lg.jp/material/files/group/13/maedatoshitsunegazou.pdf']),
71:('071_official.gif','長齢寺所蔵「前田利春画像」（石川県七尾美術館保管）','桃山時代。1581年長齢寺創建時に利家が寄進したと伝わる供養肖像。低解像度の公開画像。','Older Japanese man with shaved monk head, natural oval face and quiet expression. Light brown kosode under black translucent Buddhist robe and muted warm brown brocade kesa, as the central upper figure in the reference. The tiny low-resolution image does not resolve all facial features, so render facial volume cautiously without claiming exact likeness. No topknot, armor, attending people, tea utensils or background.',['https://www.pref.ishikawa.lg.jp/kyoiku/bunkazai/kaiga/1.html']),
73:('073_MaedaToshinaga1.jpg','長光寺（高岡市石堤）所蔵「前田利長像」／高岡市立博物館公開','歴史肖像。詳細制作年未確認。Commons2023年は画像データの日付。','Japanese man with slim oval face, fine brows, narrow eyes, clean-shaven cheeks and chin; black kanmuri with upright tip and curved rear attachment. Vermilion formal court robe and pale collar. Preserve this formal clothing instead of invented long-helmet armor. No fan, no inscription or photographic footer.',[]),
74:("074_Maeda Gen'i.jpg",'蟠桃院所蔵「前田玄以像」南化玄興賛','1602年。作者不詳。2009年は掲載書籍出版年。','Older Japanese man with shaved monk head, rounded ordinary face, low fine eyebrows and no added beard. Deep vermilion Buddhist robes and matching high folded hood resting behind the head and neck; salmon brocade kesa with light curling floral details. Preserve the monk attire and hood, no armor or topknot.',[]),
92:('092_Katō Yoshiaki.jpg','藤栄神社所蔵「加藤嘉明画像」','江戸時代とされる。東文研は藤栄神社原資料の複製に1779年の年紀と1670年の賛文を記録。','Mature Japanese man with broad oval face, slightly square jaw, fine straight brows, no added beard. Black kanmuri with upright tip and curved grey rear attachment, rich dark navy-black court robe with understated large tonal scrolling motifs and pale collar. No armor, spear or invented helmet.',['https://www.tobunken.go.jp/materials/nenki/926586.html']),
96:('096_Katō Kiyomasa.jpg','京都市勧持院所蔵「加藤清正肖像画」','江戸時代とされる。作者不詳。本人の確定的復元ではない。','Mature Japanese man, lean oval face, shaved-front small period topknot, delicate curved eyebrows, modest moustache, small soul patch and longer narrow black chin beard. Dark brown robe with repeated pale five-petal floral motifs beneath pale blue-grey dotted kataginu with white collar. Keep the reference clothing and beard; no invented spear, helmet or armor. Natural shoulders and realistically structured kataginu, not the historical flat exaggerated shoulder proportions.',[])
}
base=rows[1]['prompt'];suffix=base[base.find(' Realistic Western oil-painted'):base.find(' Current game ability')]
for i,(file,title,date,features,extra) in DETAILS.items():
    r=rows[i];assert r['status']!='generated'
    refs=[str((D/file).resolve())];assert all(Path(x).exists() for x in refs)
    if i in downloaded:sources=[downloaded[i]['url'],*extra];rights='Commons公開：古い二次元作品の忠実な複製。PD-Art／PD-old・PDM表示を確認。'
    elif i==73:sources=['https://commons.wikimedia.org/wiki/File:MaedaToshinaga1.jpg'];rights='Commons公開：PD-Art／PD-old-70・PDM表示を確認。画像下部の出典表示・額装は生成しない。'
    elif i==2:sources=extra;rights='国芳（1861年没）の江戸期武者絵。Public Domain QはPDM・CC0として公開。現代の描き起こしは参照しない。'
    else:sources=extra;rights='所蔵先・自治体が公開した、著作権保護期間の終了した歴史上の二次元絵画の忠実な複製を顔・衣装に限り参照。現代のページ文章・写真背景・装飾は再現しない。'
    r.update(reference_paths=refs,sources=sources,rights=rights,historical_source_title=title,historical_date_note=date,adopted_features=features,qa_reference_image_viewed=True,basis='本人と出所を確認した歴史資料の顔・髪・服装のみを参照。本人の実際の外見を保証する確定的復元ではない。',creative_note='自然な三次元顔・人体・胸像構図・姿勢・照明・材質を新たに描く。史料で不明瞭な細部は推定。')
    r['prompt']=f'Use case: historical-scene. Asset: modern Sengoku officer game portrait. Subject: {r["name"]}. Input image 1 is {title}, {date}, a historical reference exclusively for face, hair and clothing, NEVER an edit target or style/pose/proportion/background reference. {features} New bust composition: gentle three-quarter shoulders, face turned slightly toward viewer, calm firm natural gaze, modest dignified pose.'+suffix+f' Current game ability total {r["ability"]}/150, below 120, therefore restrained expression and pose. Keep authentic source garments; do not beautify by replacing the face or outfit. Omit every piece of calligraphy, frame, source watermark, photographic footer and background. Only one Japanese person with complete head/headgear and bust on actual alpha transparency.'
for r in rows:
    r['research_record_directory']='docs/portrait_research_20261003_102'
    if not r['reference_paths'] and r['status']!='generated':r['basis']='記録した検索で人物・伝来・年代・利用条件を確認して採用できる本人の外見画像を今回確保できず、独自創作。史料の不存在を意味しない。'
P.write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Adopted',len(DETAILS),'historical references; all physically viewed before input.')
